#!/usr/bin/env bash
#
# Ubuntu setup for Ramadan video scheduler.
# Installs dependencies, creates a venv, optionally configures Discord/location,
# and installs the systemd user service so the scheduler runs at sunrise and sundown.
#
# Usage:
#   cd /path/to/RamadanOeroen
#   chmod +x setup_ubuntu.sh
#   ./setup_ubuntu.sh
#
# Optional (non-interactive): set env vars before running
#   DISCORD_WEBHOOK_URL=... RAMADAN_LATITUDE=52.37 RAMADAN_LONGITUDE=4.9 RAMADAN_TIMEZONE=Europe/Amsterdam ./setup_ubuntu.sh
#
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"
VENV_DIR="$PROJECT_DIR/.venv"
SERVICE_NAME="ramadan-scheduler"
USER_SYSTEMD_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"

echo "=== Ramadan scheduler – Ubuntu setup ==="
echo "Project directory: $PROJECT_DIR"
echo ""

# --- 1. Check we're on something Debian/Ubuntu-like ---
if command -v apt-get &>/dev/null; then
  echo "[1/6] Using apt-get for system packages."
else
  echo "Warning: apt-get not found. Skipping system package install (install python3, python3-venv, ffmpeg yourself)."
fi

# --- 2. Install system packages (optional, may need sudo) ---
echo "[2/6] Installing system packages (python3, python3-venv, ffmpeg)..."
if command -v apt-get &>/dev/null; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq python3 python3-pip python3-venv ffmpeg
  echo "    Done."
else
  echo "    Skipped (no apt-get)."
fi

# --- 3. Create venv and install Python deps ---
echo "[3/6] Creating virtualenv and installing Python dependencies..."
if [[ -d "$VENV_DIR" ]]; then
  echo "    Venv already exists at $VENV_DIR"
else
  python3 -m venv "$VENV_DIR"
  echo "    Created $VENV_DIR"
fi
"$VENV_DIR/bin/pip" install -q --upgrade pip
"$VENV_DIR/bin/pip" install -q -r "$PROJECT_DIR/requirements.txt"
echo "    Done."

# --- 4. Optional: Discord webhook and location ---
ENV_FILE="$PROJECT_DIR/ramadan.env"
if [[ -n "$DISCORD_WEBHOOK_URL" || -n "$RAMADAN_DISCORD_WEBHOOK_URL" ]]; then
  echo "[4/6] Using Discord webhook and location from environment."
  WEBHOOK="${RAMADAN_DISCORD_WEBHOOK_URL:-$DISCORD_WEBHOOK_URL}"
  LAT="${RAMADAN_LATITUDE:-52.3676}"
  LON="${RAMADAN_LONGITUDE:-4.9041}"
  TZ="${RAMADAN_TIMEZONE:-Europe/Amsterdam}"
else
  echo "[4/6] Optional: Discord webhook and location (press Enter to skip)."
  read -p "    Discord webhook URL (or Enter to skip): " WEBHOOK
  read -p "    Latitude [52.3676]: " LAT
  LAT="${LAT:-52.3676}"
  read -p "    Longitude [4.9041]: " LON
  LON="${LON:-4.9041}"
  read -p "    Timezone [Europe/Amsterdam]: " TZ
  TZ="${TZ:-Europe/Amsterdam}"
fi

if [[ -n "$WEBHOOK" ]]; then
  cat > "$ENV_FILE" << EOF
# Generated by setup_ubuntu.sh – edit if needed
DISCORD_WEBHOOK_URL=$WEBHOOK
RAMADAN_LATITUDE=$LAT
RAMADAN_LONGITUDE=$LON
RAMADAN_TIMEZONE=$TZ
EOF
  echo "    Wrote $ENV_FILE (Discord + location)."
else
  if [[ -f "$ENV_FILE" ]]; then
    echo "    Keeping existing $ENV_FILE"
  else
    echo "    No webhook set; scheduler will run with --no-discord unless you add ramadan.env later."
  fi
fi

# --- 5. Install systemd user service ---
echo "[5/6] Installing systemd user service..."
mkdir -p "$USER_SYSTEMD_DIR"
SERVICE_FILE="$USER_SYSTEMD_DIR/$SERVICE_NAME.service"

# Write service file: venv Python, optional EnvironmentFile
{
  echo "[Unit]"
  echo "Description=Ramadan video scheduler (sunrise and sundown)"
  echo "After=network-online.target"
  echo "Wants=network-online.target"
  echo ""
  echo "[Service]"
  echo "Type=simple"
  echo "WorkingDirectory=$PROJECT_DIR"
  if [[ -f "$ENV_FILE" ]]; then
    echo "EnvironmentFile=$ENV_FILE"
  fi
  echo "ExecStart=$VENV_DIR/bin/python $PROJECT_DIR/ramadan_scheduler.py"
  echo "Restart=on-failure"
  echo "RestartSec=60"
  echo ""
  echo "[Install]"
  echo "WantedBy=default.target"
} > "$SERVICE_FILE"

echo "    Installed $SERVICE_FILE"

# --- 6. Enable and start (user or system-wide) ---
echo "[6/6] Enabling and starting scheduler..."
USE_SYSTEM_SERVICE=""
if systemctl --user daemon-reload 2>/dev/null; then
  if systemctl --user enable "$SERVICE_NAME.service" 2>/dev/null && systemctl --user start "$SERVICE_NAME.service" 2>/dev/null; then
    echo "    Service enabled and started (user session)."
  else
    USE_SYSTEM_SERVICE=1
  fi
else
  USE_SYSTEM_SERVICE=1
fi

if [[ -n "$USE_SYSTEM_SERVICE" ]]; then
  echo "    User session not available (e.g. SSH/headless). Installing system-wide..."
  SYSTEM_SERVICE="/etc/systemd/system/$SERVICE_NAME.service"
  if command -v sudo &>/dev/null; then
    sudo cp "$SERVICE_FILE" "$SYSTEM_SERVICE"
    sudo systemctl daemon-reload
    sudo systemctl enable "$SERVICE_NAME.service"
    sudo systemctl start "$SERVICE_NAME.service"
    echo "    Service enabled and started (system-wide)."
  else
    echo "    Could not enable service (no user bus and no sudo). Run manually:"
    echo "      nohup $VENV_DIR/bin/python $PROJECT_DIR/ramadan_scheduler.py >> $PROJECT_DIR/ramadan_scheduler.log 2>&1 &"
    echo "    Or copy $SERVICE_FILE to /etc/systemd/system/ and run: systemctl enable --now $SERVICE_NAME"
  fi
fi

echo ""
echo "=== Setup complete ==="
if systemctl --user status "$SERVICE_NAME" &>/dev/null; then
  echo "  Status:  systemctl --user status $SERVICE_NAME"
  echo "  Logs:    journalctl --user -u $SERVICE_NAME -f"
  echo "  Stop:    systemctl --user stop $SERVICE_NAME"
elif sudo systemctl status "$SERVICE_NAME" &>/dev/null 2>&1; then
  echo "  Status:  sudo systemctl status $SERVICE_NAME"
  echo "  Logs:    sudo journalctl -u $SERVICE_NAME -f"
  echo "  Stop:    sudo systemctl stop $SERVICE_NAME"
else
  echo "  Run:     nohup $VENV_DIR/bin/python $PROJECT_DIR/ramadan_scheduler.py >> $PROJECT_DIR/ramadan_scheduler.log 2>&1 &"
fi
echo ""
echo "The scheduler will run at sunrise and sundown for the duration of Ramadan."
[[ -f "$ENV_FILE" ]] && echo "Edit $ENV_FILE to change Discord webhook or location."
